src/routes/videojuego_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from src.models.videojuego import Videojuego
from src.models.usuario import User, ModelUser
from flask_login import login_manager, login_user,logout_user, login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from src.models.shoppingcart import ShoppingCart

videojuego_bp = Blueprint('videojuegos', __name__)


@videojuego_bp.route('/', methods=['GET'])

def index():
    videojuegos, pagination, query = Videojuego.obtener_videojuegos_paginados(request)
    
    cart = session.get("cart", {})
    
    total_quantity = sum(item['quantity'] for item in cart.values())
    
    
    total = ShoppingCart.get_total_price(cart)
    return render_template('index.html', videojuegos=videojuegos, pagination=pagination, query=query, cart=cart, total=total, total_quantity=total_quantity)

@videojuego_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']  
        password = request.form['password']

        user = User(None, None, None, email, password)
        logged_user = ModelUser.login(user)

        if logged_user is not None:
            login_user(logged_user)
            return redirect(url_for('videojuegos.index'))  
        else:
            flash('Correo o contraseña incorrectos', 'danger')
            return render_template('login.html')  
    else:    
        return render_template('login.html')
    
    
@videojuego_bp.route('/add_to_cart/<int:videojuego_id>', methods=['GET', 'POST'])
def add_to_cart(videojuego_id):
    videojuego_id = int(videojuego_id)
    # Obtener los detalles del videojuego a partir del ID
    videojuego = Videojuego.obtener_videojuego_por_id(videojuego_id)
    
    if videojuego:
        # Asegúrate de que el precio sea un número decimal (float)
        precio = float(videojuego['precio'])  # Convertir el precio a float
        print(f"Añadiendo al carrito: {videojuego['nomvideojuego']} con precio {precio}")  # Mensaje de depuración
        
        # Agregar al carrito
        ShoppingCart.add_to_cart(int(videojuego['idvideojuego']), videojuego['nomvideojuego'], precio)
        
        flash(f'{videojuego["nomvideojuego"]} añadido al carrito')  # Mensaje de éxito
    else:
        flash("Videojuego no encontrado.", "error")  # Mensaje de error si no se encuentra el videojuego
        
    return redirect(url_for('videojuegos.index'))  # Redirigir a la página de inicio (o donde lo necesites)

@videojuego_bp.route('/clear_cart')
def clear_cart():
    session.pop('cart', None)  # Elimina el carrito de la sesión
    flash("El carrito ha sido vaciado", "info")
    return redirect(url_for('videojuegos.index'))  # Redirige de nuevo a la página principal o donde desees
           

    
    

@videojuego_bp.route('/logout')
@login_required
def logout():
    session.pop('cart', None)
    logout_user()
    return redirect(url_for('videojuegos.index'))


@videojuego_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nomusuario = request.form['nomusuario']
        dni = request.form['dni']
        email = request.form['email']  
        password = request.form['password']
        
        if ModelUser.check_user_exists(email, dni, nomusuario):
            flash('El email, DNI o nombre de usuario ya están registrados. Intenta con otros datos.', 'danger')
            return redirect(url_for('videojuegos.create'))
        
        hashed_password = generate_password_hash(password)
        
        new_user = User(None, nomusuario, dni, email, hashed_password)
        
        if ModelUser.create(new_user):
            flash("Usuario registrado correctamente", "success")
            return redirect(url_for('videojuegos.create')) 
        else:
            flash("Error al registrar usuario", "danger")
            return render_template('create.html')
        
                
    return render_template('create.html')

src/templates/create.html
{% extends './layout.html' %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block body %}

{% block header %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">DeJaVu GaMeS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
            </ul>
            <a href="/login" class="btn btn-outline-success me-3">
                <i class="bi bi-person-circle"></i>
            </a>
            <form class="d-flex" role="search" method="GET" action="/">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" value="{{ query }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{% endblock %}

{% block main %}
<main class="form-signin text-center">
    <form method="POST" action="{{ url_for('videojuegos.create') }}">

        <img class="mb-4" src="{{ url_for('static', filename='images/pngegg.png') }}" alt="" width="72" height="57">

        <!-- Código para mostrar los mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br />
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}

                <div class="alert alert-info" role="alert" id="redirect-message" style="display: none;">
                    Redirigiendo a inicio de sesión...
                </div>
        
                <script>

                    document.getElementById('redirect-message').style.display = 'block';
                    // Redirige a la página de inicio de sesión después de 3 segundos
                    setTimeout(function() {
                        window.location.href = "{{ url_for('videojuegos.login') }}";
                    }, 3000);
                </script>
            {% endif %}
        {% endwith %}

        <h1 class="h3 mb-3 fw-normal">Resistro de usuario</h1>
        
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="nomusuario" name="nomusuario" placeholder="Nombre de Usuario" required>
            <label for="nomusuario">Nombre de Usuario</label>
        </div>
        
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="dni" name="dni" placeholder="DNI" required>
            <label for="dni">DNI</label>
        </div>
        
        
        <div class="form-floating mb-3">
            <input type="email" class="form-control" id="email" name="email" placeholder="Correo Electrónico" required>
            <label for="email">Correo Electrónico</label>
        </div>
        
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña" required>
            <label for="password">Contraseña</label>
        </div>

        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Registrarse</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
</main>
{% endblock %}

{% endblock %}

src/templates/index.html
{% extends './layout.html' %}



{% block header %}
<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container-fluid">
        <i class="bi bi-controller text-neon me-2" style="font-size: 1.5em;"></i>
        <a class="navbar-brand" href="/">DeJaVu GaMeS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
            </ul>

            {% if current_user.is_authenticated %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item d-flex align-items-center">
                    <!-- Ícono de controlador de videojuegos en estilo neón -->
                    
            
                    <!-- Mensaje de bienvenida en estilo neón -->
                    <h3 class="neon-text">
                        ¡Bienvenido, <span class="neon-username">{{ current_user.nomusuario }}</span>!
                    </h3>
                </li>
            </ul>
            
            <a href="#" class="btn btn-outline-success me-3">
                <i class="bi bi-cart4"></i>
            </a>

            <a href="/logout" class="btn btn-outline-danger me-3">
                <i class="bi bi-box-arrow-left"></i>
            </a>
            
            {% else %}
            

            <div class="btn-group me-3">
                <a href="/login" class="btn btn-primary active" aria-current="page">Inicia sesión</a>
                <a href="/create" class="btn btn-primary">Registrarse</a>                
            </div>

            {% endif %}

            <form class="d-flex" role="search" method="GET" action="/">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" value="{{ query }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{% endblock %}

{% block main %}
<div class="container mt-5 mb-5 ">
    <div class="row g-4">
        {% if videojuegos and videojuegos|length > 0 %}
            {% for videojuego in videojuegos %}
            <div class="col-md-4 mb-4">
                <div class="card mb-4" style="width: 20rem;">
                    <img src="{{ videojuego.nomimagen }}" class="card-img-top" alt="{{ videojuego.nomvideojuego }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ videojuego.nomvideojuego }}</h5>
                        <p class="card-price">{{ videojuego.precio }} €</p>
                        <a href="{{ url_for('videojuegos.add_to_cart', videojuego_id=videojuego.idvideojuego)}}" class="btn btn-primary">Añadir al carrito</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="col-12">
                <div class="alert alert-warning" role="alert">
                    No se encontraron resultados para tu búsqueda: <strong>{{ query }}</strong>.
                </div>
            </div>
        {% endif %}
        
    </div>
    <div class="d-flex justify-content-center">
        {{ pagination.links }}
    </div>    
</div>


<!-- Sidebar para el carrito -->
<div id="sidebarCart" class="sidebar d-flex flex-column flex-shrink-0 p-3 text-bg-dark">
    <a href="javascript:void(0)" class="closebtn" onclick="closeCart()">&times;</a>
    <h2>Tu Carrito</h2>
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}
    {% if cart %}
    <ul>
        {% for id, item in cart.items() %}
            <li>{{ item['nombre'] }} - ${{ item['precio'] }} x {{ item['quantity'] }}</li>
        {% endfor %}
    </ul>
    <h3>Total: {{ total }} € </h3>
    <a href="{{ url_for('videojuegos.clear_cart') }}">Vaciar Carrito</a>
    {% else %}
        <p>El carrito está vacío</p>
    {% endif %}    
</div>

<!-- Botón para abrir el carrito -->
<button onclick="openCart()" class="open-cart-btn btn">
    Ver Carrito
    {% if total_quantity > 0 %}
        <span class="cart-count">{{ total_quantity }}</span>

    {% endif %}
</button>

<!-- Estilos del sidebar -->
<style>
    .sidebar {
        height: 51%;
        width: 0;
        position: fixed;
        top: 66px;
        right: -32px;
        background-color: #111;
        overflow-x: hidden;
        transition: 0.5s;
        padding-top: 60px;
        color: white;
    }
    .sidebar a {
        color: white;
        display: block;
        text-decoration: none;
        padding: 10px;
        text-align: center;
    }
    .open-cart-btn {
        position: fixed;
        bottom: 10px;
        right: 10px;
        padding: 10px 20px;
        background-color: #333;
        color: white;
        border: none;
        cursor: pointer;
    }

    .open-cart-btn .cart-count {
        position: absolute;
        top: -5px;
        right: -5px;  /* Mueve la burbuja hacia la esquina superior derecha */
        width: 20px;
        height: 20px;
        background-color: #007bff; /* Color de la burbuja */
        color: white;
        font-size: 12px;
        font-weight: bold;
        text-align: center;
        border-radius: 50%;  /* Hace que la burbuja sea redonda */
        line-height: 20px;  /* Alinea el número en el centro de la burbuja */
        display: inline-block;
        min-width: 20px; /* Asegura que el número se vea bien aunque sea de un solo dígito */
    }
    
    /* Agrega un pequeño triángulo para darle estilo al contador */
    .open-cart-btn .cart-count::after {
        content: ''; /* Un pequeño triángulo */
        position: absolute;
        top: 100%;
        right: 50%;
        margin-right: -5px;
        border-width: 5px;
        border-style: solid;
        border-color: #007bff transparent transparent transparent; /* Triángulo rojo */
    }

    
</style>

<!-- JavaScript para abrir y cerrar el sidebar -->
<script>
    function openCart() {
        document.getElementById("sidebarCart").style.width = "320px";
    }
    function closeCart() {
        document.getElementById("sidebarCart").style.width = "0";
    }
</script>

{% endblock %}

{% block footer %}
<footer class="bg-dark text-light pt-5 pb-4">
    <div class="container text-center text-md-left">
        <div class="row text-center text-md-left">
            <!-- Sección de Información -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold">DeJaVu Games</h5>
                <p>
                    DeJaVu Games es tu destino para descubrir los mejores videojuegos, noticias, y reseñas de la
                    industria. ¡Explora nuestros contenidos y únete a la comunidad!
                </p>
            </div>
            <!-- Sección de Enlaces -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold">Productos</h5>
                <p>
                    <a href="#" class="text-light text-decoration-none">Juegos</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Accesorios</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Consolas</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Merchandising</a>
                </p>
            </div>
            <!-- Sección de Enlaces Útiles -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold">Enlaces útiles</h5>
                <p>
                    <a href="#" class="text-light text-decoration-none">Tu cuenta</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Afiliados</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Soporte</a>
                </p>
                <p>
                    <a href="#" class="text-light text-decoration-none">Términos y Condiciones</a>
                </p>
            </div>
            <!-- Sección de Redes Sociales -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold">Contacto</h5>
                <p><i class="fas fa-home mr-3"></i> Madrid, España, 27777</p>
                <p><i class="fas fa-envelope mr-3"></i> info@dejavugames.com</p>
                <p><i class="fas fa-phone mr-3"></i> 696 697 698</p>
                <p><i class="fas fa-print mr-3"></i> 696 697 698</p>
            </div>
        </div>
        <!-- Línea divisoria -->
        <hr class="mb-4">
        <!-- Sección de Copyright -->
        <div class="row align-items-center">
            <div class="col-md-7 col-lg-8">
                <p class="text-center text-md-left">
                    © 2024 GameZone - Todos los derechos reservados.
                </p>
            </div>
            <div class="col-md-5 col-lg-4">
                <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a href="#" class="btn btn-outline-light btn-floating text-light"><i
                                    class="fab fa-facebook-f"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="btn btn-outline-light btn-floating text-light"><i
                                    class="fab fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="btn btn-outline-light btn-floating text-light"><i
                                    class="fab fa-instagram"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="btn btn-outline-light btn-floating text-light"><i
                                    class="fab fa-youtube"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Enlaces de FontAwesome para iconos -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

{% endblock %}

src/templates/layout.html
<!doctype html>

<html lang="es">
<head>
    <meta charset="utf-8" />
    <title>Videojuegos</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.3.2 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    
    <!-- Custom CSS -->
    {% block customCSS %}
    {% endblock %}
</head>

<body>
    {% block body %}
    <header>
        <!-- place navbar here -->
        {% block header %}
        {% endblock %}
    </header>
    <main>
        {% block main %}
        {% endblock %}

    </main>
    <footer>
        <!-- place footer here -->
        {% block footer %}
        {% endblock %}
    </footer>
    {% endblock %}
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/login.html
{% extends './layout.html' %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
{% endblock %}

{% block body %}

{% block header %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">DeJaVu GaMeS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
            </ul>

            <form class="d-flex" role="search" method="GET" action="/">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" value="{{ query }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{% endblock %}

{% block main %}
<main class="form-signin text-center">
    <form method="POST" action="{{ url_for('videojuegos.login') }}">

        <img class="mb-4" src="{{ url_for('static', filename='images/pngegg.png') }}" alt="" width="72" height="57">

        <!-- Código para mostrar los mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br />
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    
        <div class="form-floating">
            <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="">
            <label for="email">Email address</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="">
            <label for="password">Password</label>
        </div>
    
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
</main>
{% endblock %}

{% endblock %}